### ISSUE TITLE
Structure matching shows 0 matches, but there is at least 1

### ISSUE THREAD

**Issue by dennisrd** [TNO/vscode-tracy#49]
Found this issue in [f432b0b](https://github.com/TNO/vscode-tracy/commit/f432b0b458de23a7163ca303bcf49193a8f3e6d8).

Using example data file [vacation.csv](https://github.com/TNO/vscode-tracy/blob/main/test/data/vacation.csv)

Actions to reproduce the issue:
- Open the file in Tracy (using the standard CSV converter).
- Select (Ctrl-click) a row, e.g. the row of 2023-08-14 (which has Action "leaving on vacation").
- Create a structure from the selected row (using the structure button).
- In the Structure Matching pop-up, click "Search for Structure".

Expected result: at least 1 occurrence of the structure is found (namely the row itself from which the structure was created).

Observed result: no matches ("0 of 0").

**Comment by LightFLP** [comment]
@dennisrd I think I may have found the origin of the bug. Today, I tried to test something on the `vacation.csv` and the Structure Matching did not work properly. I noticed that in VS Code the break type of the file is **CRLF**, which adds carriage returns on each line of the file (including the first line, containing the headers). When switching this break type to **LF**  the Structure Matching works properly.

To address this issue I have added a small check for carriage returns in the headers of the log (since this part was missing and was causing the bug). Now the Structure Matching works for both **CRLF** .csv files and **LF** .csv files.

I will close this issue as resolved.
